drop table Arbitros if exists
drop table Equipos if exists
drop table Jugadores if exists
drop table Partidos if exists
drop table Polideportivos if exists
drop table Temporadas if exists
create table Arbitros (arbitro_id bigint generated by default as identity unique, calle varchar(255) not null, ciudad varchar(255) not null, codigo_postal varchar(255) not null, provincia varchar(255) not null, numero_colegiado varchar(255) not null unique, apellido1 varchar(255) not null, apellido2 varchar(255), dni varchar(255) not null, nombre varchar(255) not null, primary key (arbitro_id))
create table Equipos (equipo_id bigint generated by default as identity unique, nombre varchar(255) not null, temporada bigint, primary key (equipo_id), unique (temporada, nombre))
create table Jugadores (jugador_id bigint generated by default as identity unique, capitan BIT not null, apellido1 varchar(255) not null, apellido2 varchar(255), dni varchar(255) not null, nombre varchar(255) not null, equipo bigint, temporada bigint, primary key (jugador_id), unique (temporada, dni), unique (equipo, dni))
create table Partidos (partido_id bigint generated by default as identity unique, fecha timestamp not null, arbitro bigint, local bigint, polideportivo bigint, temporada bigint, visitante bigint, primary key (partido_id), unique (temporada, local, visitante))
create table Polideportivos (polideportivo_id bigint generated by default as identity unique, campos_disponibles integer not null, calle varchar(255) not null, ciudad varchar(255) not null, codigo_postal varchar(255) not null, provincia varchar(255) not null, nombre varchar(255) not null, primary key (polideportivo_id))
create table Temporadas (temporada_id bigint generated by default as identity unique, fecha_fin date not null, fecha_inicio date not null, primary key (temporada_id), unique (fecha_inicio, fecha_fin))
alter table Equipos add constraint FK983C1F4B28637EA foreign key (temporada) references Temporadas
alter table Jugadores add constraint FK498EDFD0B28637EA foreign key (temporada) references Temporadas
alter table Jugadores add constraint FK498EDFD0AB43CB22 foreign key (equipo) references Equipos
alter table Partidos add constraint FK4AB6D6D2688BA00C foreign key (visitante) references Equipos
alter table Partidos add constraint FK4AB6D6D2B28637EA foreign key (temporada) references Temporadas
alter table Partidos add constraint FK4AB6D6D2FEA10C4E foreign key (local) references Equipos
alter table Partidos add constraint FK4AB6D6D2C38092A4 foreign key (polideportivo) references Polideportivos
alter table Partidos add constraint FK4AB6D6D2175612CE foreign key (arbitro) references Arbitros